################################################################################################################
# Site settings                                                                                             #
################################################################################################################
remote_theme: hydecorp/hydejack@v9.0.5

################################################################################################################
# General settings                                                                                             #
################################################################################################################

lang: #  default language is en I think it as global may be change later translated branch wise
title: Adobe Commerce Cloud Developer Expert Certification - (ADO-706)
short_title: Adobe Commerce Cloud Developer Expert Certification
description: Adobe Commerce Cloud Developer Expert Certification  (ADO-706).
tagline: “Adobe Commerce Cloud Developer Expert Certification (ADO-706)”.
url: https://lalittmohan.github.io/Adobe-Commerce-Cloud-Developer-Expert-Certification/
baseurl: /
keywords: [
  'Magento',
  'Magento 2',
  'adobe commerce cloud',
  'magento2 certification',
  'adobe commerce cloud certification course',
  'magento2 certified',
  'Adobe commerce certification',
  'Adobe certified cloud exam',
  'certification',
  'magento2 study-guide',
  'adobe commerce study-guide'
  ]
  
author:
  # Used by `jekyll-feed`:
  name: Lalit Mohan
  email: lalitmohanwd@gmail.com
  # # Used by `jekyll-seo-tag`:
  twitter: lalittmohan
  github: lalittmohan
  instagram: lalitmohann
  linkedin: lalittmohan

  ## => GitHub Repository (if the site is hosted by GitHub)
  ##############################
  repository: lalittmohan/Adobe-Commerce-Cloud-Developer-Expert-Certification
  repository_tree: master

## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg

## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx

## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  
# Add links to the sidebar
menu:
  - title: 01 - Commerce Cloud Fundamentals
    url:   /commerce-cloud-fundamentals
  - title: 02 - Local Environment
    url:   /local-environment
  - title: 03 - Cloud Configuration
    url:   /cloud-configuration
  - title: 04 - Service Configuration
    url:   /service-cofiguration
  - title: 05 - Deployment Process
    url:   /deployment-process
  - title: 06 - Static Content Deployment
    url:   /satic-content-deployment
  - title: 07 - Development
    url: /development
  - title: 08 - Troubleshooting
    url: /troubleshooting
  - title: 09 - Go Live and Maintenance
    url: /go-live-and-maintenance

no_search: false
accent_image: none
accent_color: rgb(219,44,44)

## => Plugins
##############################
##plugins:
#  - jekyll-feed
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jemoji

## [![](https://mermaid.ink/img/eyJjb2RlIjoic3RhdGVEaWFncmFtLXYyXG4gICBcbiAgICBzdGF0ZSBjZXJ0aWZpY2F0aW9uIHtcbiAgICAgICAgWypdIC0tPiBzdHVkeV9ndWlkZVxuICAgICAgICBzdGF0ZSBjb25jZXB0X2Jvb2t7XG4gICAgICAgICAgICBbKl0gLS0-IHRhc2tib29va1xuXG4gICAgICAgIH1cbiAgICAgICAgIHN0YXRlIHRhc2tib29va3tcbiAgICAgICAgIFsqXSAtLT4gY29uY2VwdF9ib29rXG4gICAgICAgIFxuICAgICAgICB9XG4gICAgICAgIG5vdGUgcmlnaHQgb2YgdGFza2Jvb29rXG4gICAgICAgICAgICBzb2x1dGlvbnMgZm9yIGJhc2ljIHRhc2sgPDYwIG1pbi5cbiAgICAgICAgICAgIGxpc3Qgb2Ygc21hbGwgcGFydCBvZiBiaWcgZmVhdHVyZXMuXG4gICAgICAgICAgICByZWFsIGJ1c2luZXNzIHJlcS4gc2NlbmVyaW8gYmFzZWQgc29sdXRpb25zLlxuICAgICAgICBlbmQgbm90ZVxuICAgICAgICBzdHVkeV9ndWlkZSAtLT4gY29uY2VwdF9ib29rOiBleHBsb3JlIHRvcGljIHdpc2VcbiAgICAgICAgc3R1ZHlfZ3VpZGUgLS0-IGRldmRvY3M6IGV4cGxvcmUgdG9waWMgd2lzZVxuICAgICAgICBkZXZkb2NzIC0tPiBjb25jZXB0X2Jvb2tcbiAgICAgICAgc3R1ZHlfZ3VpZGUgLS0-IHN0dWR5X2dyb3VwOndlZWtseSBtZWV0IFxuICAgICAgICBzdHVkeV9ncm91cCAtLT4gY29uY2VwdF9ib29rXG4gICAgICAgIGNvbmNlcHRfYm9vayAtLT4gc3R1ZHlfZ3JvdXBcbiAgICAgICAgdGFza2Jvb29rIC0tPiBbKl1cbiAgICAgICAgbm90ZSByaWdodCBvZiBjb25jZXB0X2Jvb2tcbiAgICAgICAgICAgIEV4cGxvcmUgSG93IGl0J3Mgd29ya3MgdG9waWMgd2lzZS5cbiAgICAgICAgICAgIENvdmVyIERlc2lnbiBQYXR0ZXJucy5cbiAgICAgICAgICAgIENvZGUgRmxvdyAmIEJ1c2luZXNzIExvZ2ljLlxuICAgICAgICAgICAgQmFzaWMgdGhlb3JpZXMgJiBSZXNvdXJjZSBMaW5rcy5cbiAgICAgICAgZW5kIG5vdGVcbiAgICB9XG4gICBcbiAgbm90ZSBsZWZ0IG9mIGNlcnRpZmljYXRpb25cbiAgICAgICAgICAgIGNvbmNlcHQgYm9vazogW0dpdGh1YiBSZXBvc2l0b3J5XS5cbiAgICAgICAgICAgIHRhc2sgYm9vazogW0dpdGh1YiBSZXBvc2l0b3J5XS5cbiAgICAgICAgZW5kIG5vdGVcbiAgICBcbiAgIFxuICAgICAgICAgICAgIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ)](https://mermaid.live/edit#eyJjb2RlIjoic3RhdGVEaWFncmFtLXYyXG4gICBcbiAgICBzdGF0ZSBjZXJ0aWZpY2F0aW9uIHtcbiAgICAgICAgWypdIC0tPiBzdHVkeV9ndWlkZVxuICAgICAgICBzdGF0ZSBjb25jZXB0X2Jvb2t7XG4gICAgICAgICAgICBbKl0gLS0-IHRhc2tib29va1xuXG4gICAgICAgIH1cbiAgICAgICAgIHN0YXRlIHRhc2tib29va3tcbiAgICAgICAgIFsqXSAtLT4gY29uY2VwdF9ib29rXG4gICAgICAgIFxuICAgICAgICB9XG4gICAgICAgIG5vdGUgcmlnaHQgb2YgdGFza2Jvb29rXG4gICAgICAgICAgICBzb2x1dGlvbnMgZm9yIGJhc2ljIHRhc2sgPDYwIG1pbi5cbiAgICAgICAgICAgIGxpc3Qgb2Ygc21hbGwgcGFydCBvZiBiaWcgZmVhdHVyZXMuXG4gICAgICAgICAgICByZWFsIGJ1c2luZXNzIHJlcS4gc2NlbmVyaW8gYmFzZWQgc29sdXRpb25zLlxuICAgICAgICBlbmQgbm90ZVxuICAgICAgICBzdHVkeV9ndWlkZSAtLT4gY29uY2VwdF9ib29rOiBleHBsb3JlIHRvcGljIHdpc2VcbiAgICAgICAgc3R1ZHlfZ3VpZGUgLS0-IGRldmRvY3M6IGV4cGxvcmUgdG9waWMgd2lzZVxuICAgICAgICBkZXZkb2NzIC0tPiBjb25jZXB0X2Jvb2tcbiAgICAgICAgc3R1ZHlfZ3VpZGUgLS0-IHN0dWR5X2dyb3VwOndlZWtseSBtZWV0IFxuICAgICAgICBzdHVkeV9ncm91cCAtLT4gY29uY2VwdF9ib29rXG4gICAgICAgIGNvbmNlcHRfYm9vayAtLT4gc3R1ZHlfZ3JvdXBcbiAgICAgICAgdGFza2Jvb29rIC0tPiBbKl1cbiAgICAgICAgbm90ZSByaWdodCBvZiBjb25jZXB0X2Jvb2tcbiAgICAgICAgICAgIEV4cGxvcmUgSG93IGl0J3Mgd29ya3MgdG9waWMgd2lzZS5cbiAgICAgICAgICAgIENvdmVyIERlc2lnbiBQYXR0ZXJucy5cbiAgICAgICAgICAgIENvZGUgRmxvdyAmIEJ1c2luZXNzIExvZ2ljLlxuICAgICAgICAgICAgQmFzaWMgdGhlb3JpZXMgJiBSZXNvdXJjZSBMaW5rcy5cbiAgICAgICAgZW5kIG5vdGVcbiAgICB9XG4gICBcbiAgbm90ZSBsZWZ0IG9mIGNlcnRpZmljYXRpb25cbiAgICAgICAgICAgIGNvbmNlcHQgYm9vazogW0dpdGh1YiBSZXBvc2l0b3J5XS5cbiAgICAgICAgICAgIHRhc2sgYm9vazogW0dpdGh1YiBSZXBvc2l0b3J5XS5cbiAgICAgICAgZW5kIG5vdGVcbiAgICBcbiAgIFxuICAgICAgICAgICAgIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)
